language: php
sudo: false
php:
  - 5.6
  - 7.0.15

before_script:
  - cp tests/bootstrap.php.dist tests/bootstrap.php
  - composer install


script:
  - ./vendor/bin/phplint
  - cd vendor
  - ./phpunit/phpunit/phpunit ../tests/